### ISSUE TITLE
[Feature Request] Hide entity based on attributes 

### ISSUE THREAD

**Issue by djlukas7** [joBr99/nspanel-lovelace-ui#652] opened 2022-12-30 10:00 UTC
Is it possible to hide an entity based on its attribute. I mean something like this:
The entity has a days attribute and I would like to hide all entities that have a days attribute less than 7.
I've seen that I can hide an entity based on its on/off state but I don't know how to hide an entity based on its attributes.

![obraz](https://user-images.githubusercontent.com/75642617/210057581-115c4d75-4383-4b1c-9e10-f1cd1f33be41.png)

I would like to get the effect like in the picture above, because I have 5 entities and they just don't fit in the cardEntities screen.
cardEntities can only display 4 entities.

Sorry for my English.

**Comment by joBr99** [comment] 2022-12-30 10:08
You can use this:
https://docs.nspanel.pky.eu/entities/?h=state#hide-item-based-on-state

It was intended for binary_sensors and you cannot do comparisons, so you end up with 35 entities, but it should work.

Note that there is currently a bug and state/state_not are swapped, which will be fixed in next version.

```
      - entity: sensor.zmieszane
        state_not: 0
      - entity: sensor.zmieszane
        state_not: 1
      - entity: sensor.zmieszane
        state_not: 2
      - entity: sensor.zmieszane
        state_not: 3
      - entity: sensor.zmieszane
        state_not: 4
      - entity: sensor.zmieszane
        state_not: 5
      - entity: sensor.zmieszane
        state_not: 6
```

**Comment by djlukas7** [comment] 2022-12-30 10:31
Unfortunately, it doesn't work

![obraz](https://user-images.githubusercontent.com/75642617/210060281-d174d9f9-b552-4372-8f0e-bd9ba7ff362e.png)

![Image 2022-12-30 at 11 30 22](https://user-images.githubusercontent.com/75642617/210060629-eec82051-84cb-4899-9a46-2c7aa223dabb.jpeg)

**Comment by joBr99** [comment] 2022-12-30 10:34
please try `state` instead of `state_not`

if it doesn't work please add a picture of the states of this entity from developer tools

and if there are any errors in the appdaemon log also the log

**Comment by djlukas7** [comment] 2022-12-30 10:47
Log with "state_not":
![obraz](https://user-images.githubusercontent.com/75642617/210061314-5eda175c-49e2-4624-9313-d946a8febf08.png)

Log with "state":
![obraz](https://user-images.githubusercontent.com/75642617/210061847-a5f8b929-692f-4637-b901-87af9597979f.png)

Screen from nspanel with "state":
![Image 2022-12-30 at 11 43 45](https://user-images.githubusercontent.com/75642617/210061985-edef886e-3ff8-4c44-ad7b-70dd9669d1e6.jpeg)

States from developer tools:
![obraz](https://user-images.githubusercontent.com/75642617/210061584-d5c86754-7bbd-4c2a-adb8-e1ab9f07c9e0.png)

**Comment by joBr99** [comment] 2022-12-30 10:58
ah ok; state and state_not are checking for state and not for "days" so this isn't going to work this way

**Comment by djlukas7** [comment] 2022-12-30 11:21
Could "state_attr" work? I just don't know exactly how to use it. In the documentation is:
icon: 'ha:{{state_attr("climate.wohnzimmer_boden","current_temperature")}}'
but this turns the icon into an entity value.
I will try somthing like this:
state: 'ha:{{ state_attr("sensor.zmieszane","days") <7 }}'
But it doesn't work.

**Comment by joBr99** [comment] 2022-12-30 13:01
Update your backend and the firmware to current development version.
https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version

After that you can use:

```yaml
      - entity: binary_sensor.sensor_kueche_contact
        state_template: '{{ state_attr("sun.sun","azimuth") < 200 }}'
```

**Closed** 2022-12-30 13:02 UTC
Labels: question, configuration

**Comment by djlukas7** [comment] 2022-12-30 13:09
It works perfectly. Thank you very much
