### ISSUE TITLE
[Bug] Check small font on US-P

### ISSUE THREAD

**Issue by ClaireRovic** [joBr99/nspanel-lovelace-ui#802] opened 2023-03-07 03:03 UTC
### FEATURE DESCRIPTION
To be able to reduce the font size on the mediaCard for the lower Entity line. 

### ADDITIONAL CONTEXT
Typically radio stations in Australia have a 3 letter code, if used as the Name I get character chopped off. Image will be attached.

### PANEL / FIRMWARE VERION
US-P
![1677579154165](https://user-images.githubusercontent.com/52806118/223309470-646a33ce-6073-4a1b-8a30-1f415d32abcd.jpg)

**Comment by joBr99** [comment] 2023-08-24 14:49
With the latest development tft file you can change the font like this:

`            icon: "text:X¬0"`

The number is the number of the font in nextion.

Handling will probably change a bit so there's another option like `font` in the yaml, however it works already this way.

Further changes will be done in #964

**Comment by ClaireRovic** [comment] 2023-08-31 04:21
Thanks heaps - will wait for Production version - do you have a concept on when this will be - thanks sent a pizza

**Comment by ClaireRovic** [comment] 2023-09-22 08:30
Was trying to implement the small font as per the resent update US-P. I did not change the font size, hoping I have done something wrong.

`type: cardMedia
title: Study Radio
key: studyRadioKey
sleepTimeout: 90
navItem1:
  entity: navigate.ssKey
  icon: mdi:home
  color: [55, 55, 55]
navItem2:
  entity: navigate.studyDetailKey
  icon: mdi:arrow-up-bold
  color: [55, 55, 55]
entity: input_select.speakers
status: media_player.study_speaker
entities:
  - entity: service.script.turn_on
    font: small
    icon: text:SM
    data:
      entity_id: script.radio_player
      variables:
        radio_id: Smooth
        radio_type: music
        speaker_id: Study`

**Comment by joBr99** [comment] 2023-10-14 14:46
![PXL_20231014_144329779](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/e5d0b6b5-85d6-4131-aa74-18ed40a12813)

**Comment by joBr99** [comment] 2023-10-14 15:16
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/0e156974-2f65-43ac-833e-2b3b4c9b277c)

Confirmed cardMedia working aswell, please check if you are on the latest version and restart appdaemon.

**Comment by ClaireRovic** [comment] 2023-10-23 09:47
Thankyou for all your effort and focus. Hopefully you can help me on where I have gone wrong. If I use "text:91.91¬0" it does appear to work very well, though 'font: small'  does nothing.

**Comment by joBr99** [comment] 2023-10-25 19:12
Hey,
discovered this bug

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/f56faf0b-3116-4d67-b4db-bf8322dc5d1f)

```yaml
      - type: cardMedia
        title: Kitchen
        entity: media_player.kitchen
        entities:
          - entity: light.bed_light
            icon: text:tex
            font: small
          - entity: light.bed_light
            icon: text:text
            font: medium
```

String is sent to the panel twice, which is probably the cause for your problem with the font size, as the string is getting to long and cut off.

**Comment by joBr99** [comment] 2023-10-25 19:17
should be fixed in newest version

**Closed** 2023-10-25 19:16 UTC

**Comment by ClaireRovic** [comment] 2023-10-28 00:25
Thanks Heaps, not overly worried at the moment as your other approach works quiet well. Enjoy, due to inflation half a pizza on its way 😂🤣
