### ISSUE TITLE
[BUG] iobroker: Some Bugfixes (again)

### ISSUE THREAD

**Issue by Grrzzz** [joBr99/nspanel-lovelace-ui#286] opened 2022-06-16 11:15 UTC
Last time - promise.
This time last 3 bugs which annoyed me were fixed:
1. Bug in findPageElement fixed
   This caused in some cases that PopupDetailPage was incomplete, as PageElement was not found
2. Live state updates in Sub-Pages fixed
   That bug was actually caused by me and is fixed again
3. Exit on Detail Page returning to wrong page ("bexit" action)
   Again - on subpages. Fixed now

The usual:
 https://www.textcompare.org/?id=62ab10d4ffa49a28af330a97

**Comment by Armilar** [comment] 2022-06-16 20:44
merged

**Comment by Armilar** [comment] 2022-06-17 11:30
But if I now open a page, e.g. cardMedia in the main menu, then the page is no longer available and another page is displayed instead

**Comment by Grrzzz** [comment] 2022-06-21 07:55
Sorry for just coming back to you.
I am unable to reproduce described behavior.
What I did not in your sample config is the following:
You are defining "parent" pages to main pages as well. i.e:

Currently:
```
var Test_Licht: PageEntities =
{
    "type": "cardEntities",
    "heading": "Color Aliase",
    "useColor": true,
    "subPage": false,
    "parent": Test_Licht,
    "items": [
        <PageItem>{ id: "alias.0.NSPanel_1.TestRGBLichteinzeln", name: "RGB-Licht Hex-Color", interpolateColor: true},
        //<PageItem>{ id: "alias.0.NSPanel_1.TestFarbtemperatur", name: "Farbtemperatur", interpolateColor: true},
        <PageItem>{ id: "alias.0.NSPanel_1.TestRGBLicht", name: "RGB-Licht", minValueBrightness: 0, maxValueBrightness: 100, interpolateColor: true},
        <PageItem>{ id: "alias.0.NSPanel_1.TestCTmitHUE", name: "HUE-Licht-CT", minValueBrightness: 0, maxValueBrightness: 70, minValueColorTemp: 500, maxValueColorTemp: 6500, interpolateColor: true},
        <PageItem>{ id: "alias.0.NSPanel_1.TestHUELicht", name: "HUE-Licht-Color", minValueColorTemp: 500, maxValueColorTemp: 6500, interpolateColor: true}
    ]
};
```

Should:
```
var Test_Licht: PageEntities =
{
    "type": "cardEntities",
    "heading": "Color Aliase",
    "useColor": true,
    "subPage": false,
    "parent": undefined,
    "items": [
        <PageItem>{ id: "alias.0.NSPanel_1.TestRGBLichteinzeln", name: "RGB-Licht Hex-Color", interpolateColor: true},
        //<PageItem>{ id: "alias.0.NSPanel_1.TestFarbtemperatur", name: "Farbtemperatur", interpolateColor: true},
        <PageItem>{ id: "alias.0.NSPanel_1.TestRGBLicht", name: "RGB-Licht", minValueBrightness: 0, maxValueBrightness: 100, interpolateColor: true},
        <PageItem>{ id: "alias.0.NSPanel_1.TestCTmitHUE", name: "HUE-Licht-CT", minValueBrightness: 0, maxValueBrightness: 70, minValueColorTemp: 500, maxValueColorTemp: 6500, interpolateColor: true},
        <PageItem>{ id: "alias.0.NSPanel_1.TestHUELicht", name: "HUE-Licht-Color", minValueColorTemp: 500, maxValueColorTemp: 6500, interpolateColor: true}
    ]
};
```

Please note line
`    "parent": undefined,`

All "mainpages" (pages listed in config.pages) should have parent=undefined

Maybe this already resolves your issue?

**Comment by Armilar** [comment] 2022-06-21 14:37
No, the problem is not solved yet

I have adjusted the code (Config/bExit) according to the last remarks.

I'll try to describe it a little better.

If the cardEntities or the cardGrid is defined as the main page without a subpage and is open, the screensaver comes after the timeout. When I push the screensaver away, the same page that I had previously opened opens. All is well.

If cardThermo, cardMedia or cardAlarm is open as the main page, the screensaver also appears after the timeout. If I now push the screensaver away, I no longer have the same page, but the previous one. Only through several pages of the menu do I get back to one of these pages.

**Comment by joBr99** [comment] 2022-06-21 14:49
@Armilar I will fix this issue with the bot later

**Comment by Grrzzz** [comment] 2022-06-24 17:55
Ok - got it. 
Unfortunately, I do not use any of those mentioned page-types. I tried to reproduce it with faulty dummy pages, and even then, I was unable to see your described behavior. With any given _main_ page (!listed under config.pages!), i was ALWAYS getting back to the last opened page after the screensaver poped up.

So I am actually unable to fix that.

**Closed** 2022-07-10 08:13 UTC
Labels: bug, ioBroker
