### ISSUE TITLE
Model does not match

### ISSUE THREAD

**Issue by burghs** [joBr99/nspanel-lovelace-ui#30] opened 2022-03-10 07:01 UTC
Hi there,

I am trying to flash my NSPanel with the nspanel.tft supplied in the git repository. The file is uploaded to a local webserver and from the console it shows the following:

_07:53:01.119 CMD: flashnextion http://192.168.1.32/uploads/nspanel.tft
07:53:01.140 MQT: stat/nspanel/RESULT = {"FlashNextion":"Done"}
07:53:01.228 connected: true
07:53:01.234 Downloading Byte 0 - 0
07:53:01.366 Content-Range: bytes 0-0/196832
07:53:01.377 NSP: Sent = bytes('4452414B4A485355594447424E434A48474A4B534842444EFFFFFF')
07:53:01.388 NSP: Sent = bytes('7265636D6F643D30FFFFFF')
07:53:01.395 NSP: Sent = bytes('7265636D6F643D30FFFFFF')
07:53:01.401 NSP: Sent = bytes('636F6E6E656374FFFFFF')
07:53:01.406 NSP: Sent = bytes('636F6E6E656374FFFFFF')
07:53:01.421 NSP: Received Raw = bytes('636F6D6F6B20322C33303631342D302C4E5834383332463033355F303131432C...')
07:53:01.430 NSP: Sent = bytes('77686D692D777269203139363833322C3131353230302C31FFFFFF')
07:53:01.520 NSP: Received Raw = bytes('636F6D6F6B20322C33303631342D302C4E5834383332463033355F303131432C...')
07:53:01.530 NSP: Sent = bytes('77686D692D777269203139363833322C3131353230302C31FFFFFF')
07:53:01.919 NSP: Received Raw = bytes('05')
07:53:01.926 rec 0x05
07:53:01.929 current chunk empty
07:53:01.948 connected: true
07:53:01.953 Downloading Byte 0 - 32767
07:53:02.710 Flashing Progress ( 4096 / 196832 ) [ 2 ]
07:53:02.724 MQT: tele/nspanel/RESULT = {"Flashing":{"complete": 2}}_

On the NSPanel however it briefly goes to a black flash screen and then changes to a white display with the following:
Model does not match
Device Model:
NX4832F035_011C

 (I have the EU version of the panel so not sure if this is why?)

**Comment by joBr99** [comment] 2022-03-10 07:03
Hey, sounds like an issue with your webserver, try the following command.

`FlashNextion http://nspanel.pky.eu/lui.tft`

**Comment by burghs** [comment] 2022-03-10 07:09
> Hey, sounds like an issue with your webserver, try the following command.
> 
> `FlashNextion http://nspanel.pky.eu/lui.tft`

spot on, tried your link and it seems to be flashing now. thanks for the quick response!

**Comment by joBr99** [comment] 2022-03-10 07:26
still wondering what's going on with your webserver, looks like it did send the correct header, but not the correct data/file

can you send me the output of the following command (linux command, not tasmota) and tell me which webserver you're using?

`curl -v -X GET --output - -H "range: bytes=1-100" http://192.168.1.32/uploads/nspanel.tft`

**Comment by joBr99** [comment] 2022-03-10 07:29
related to #2

**Comment by joBr99** [comment] 2022-03-10 07:31
Duplicate of #2

**Comment by burghs** [comment] 2022-03-10 07:36
> still wondering what's going on with your webserver, looks like it did send the correct header, but not the correct data/file
> 
> can you send me the output of the following command (linux command, not tasmota) and tell me which webserver you're using?
> 
> `curl -v -X GET --output - -H "range: bytes=1-100" http://192.168.1.32/uploads/nspanel.tft`

Created a web server running on IIS as my Home Assistant is on https which i had trouble with flashing with before.

here is the result:

*   Trying 192.168.1.32:80...
* Connected to 192.168.1.32 (192.168.1.32) port 80 (#0)
> GET /uploads/nspanel.tft HTTP/1.1
> Host: 192.168.1.32
> User-Agent: curl/7.79.1
> Accept: */*
> range: bytes=1-100
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 206 Partial Content
< Content-Type: extention/lcddisplay
< Last-Modified: Thu, 10 Mar 2022 05:48:50 GMT
< Accept-Ranges: bytes
< ETag: "206e2844234d81:0"
< Server: Microsoft-IIS/10.0
< Date: Thu, 10 Mar 2022 07:32:06 GMT
< Content-Length: 100
< Content-Range: bytes 1-100/196832

**Comment by joBr99** [comment] 2022-03-10 07:39
is there content after the head in the output of curl? the answer to my request looks like this

```
* Mark bundle as not supporting multiuse
< HTTP/1.1 206 Partial Content
< Cache-Control: public, max-age=2678400
< Content-Type: application/octet-stream
< Etag: "16d1e4f0f6c917ff-42318"
< Last-Modified: Tue, 08 Feb 2022 19:04:23 GMT
< Content-Length: 100
< Accept-Ranges: bytes
< Content-Range: bytes 1-100/271128
< Date: Thu, 10 Mar 2022 07:38:00 GMT
< Server: Python/3.9 aiohttp/3.8.1
<
* Connection #0 to host 192.168.75.30 left intact
?N2E@@d2Ev!#sn
```

**Closed** 2022-03-10 17:53 UTC
Labels: duplicate, display-flashing
